
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sprovider from "@/components/Sprovider";
import Nav from "@/components/Nav";
import { cn } from "@/lib/utils";

import { Providers } from "@/lib/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DoodleBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <Providers >
        <Sprovider>
          <body className={cn(inter.className, 'relative flex flex-col overflow-hidden')}>
            <Nav />
            {children}
          </body>
        </Sprovider>
      </Providers>
    </html>
  );
}
